"""
Simulation for the funding-proposal demo:
"Deviations from autonomous behaviour as signals of external perturbations"
realised on the BudgetODMR CW FM-lock-in NV magnetometer.

The physical system is the existing two-point/side-of-fringe frequency lock
(smcv/odmr_fieldlock_fm_pc.py) viewed as a DYNAMICAL SYSTEM. One loop cycle is
the discrete map

    f_{k+1} = f_k - (G / D_cal) * [ R(f_k - c) - R_0 ]                    (1)

where R(x) is the FM lock-in lobe shape (|dL/df| of the ODMR line), c the line
centre, R_0 the setpoint on a lobe flank and D_cal the slope measured at
calibration time. Linearising around the fixed point, the error obeys
eps_{k+1} = (1 - G_eff) eps_k with the DIMENSIONLESS loop gain

    G_eff = G * R'(x*) / D_cal .                                          (2)

|1 - G_eff| < 1 is a stable lock; at G_eff = 2 the map undergoes a flip
(period-doubling) bifurcation and the loop becomes an AUTONOMOUS self-
oscillator -- a limit cycle generated by the device itself, no external clock
or drive, cascading to chaos at higher gain (like a driven Josephson junction).

Sensing principle demonstrated here:
  * a UNIFORM field only translates the line -> the lock re-centres, the
    dynamics are invariant (shift symmetry) -> DC field = mean of the loop;
  * anything that changes the lobe SLOPE -- a field GRADIENT across the
    ensemble (inhomogeneous broadening), MW/laser power, temperature/linewidth,
    unresolved fast AC fields -- changes G_eff and therefore moves the
    oscillation ONSET: the appearance/disappearance of the autonomous limit
    cycle is the sensor output (cf. Josephson bifurcation amplifier);
  * time-periodic perturbations imprint themselves on the limit-cycle
    STATISTICS (cycle-amplitude envelope, two-time correlations).

Model assumptions: Lorentzian line of fixed contrast, so the FM lobe amplitude
and slope scale as 1/(1+beta) when the linewidth is broadened by (1+beta);
Gaussian readout noise per cycle. Parameters mirror the real rig (lobe peak
~10 mV, per-reading noise ~0.3 mV, 20 cycles/s).

Run:  python autonomous_nv_sim.py     (writes fig1..fig5.png next to itself)
"""

import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
rng = np.random.default_rng(11)

# ---- rig-like parameters -------------------------------------------------
HW      = 0.75        # ODMR half-width Gamma/2 [MHz]
RPK     = 0.010       # FM lobe peak [V] (as on the rig, ~10 mV)
SIG_R   = 3e-4        # readout noise per cycle [V] (~3 % of peak)
DT      = 0.05        # loop cycle time [s] (~20 cycles/s on the rig)
CLIP    = 8.0         # actuator range [MHz] (sweep-span clip)


def lobe(x, beta=0.0):
    """FM lock-in lobe |dL/df| for a Lorentzian of fixed contrast whose width
    is broadened by (1+beta). Positive x = detuning from the line centre."""
    hw = HW * (1.0 + beta)
    s = 2 * hw**2 * np.abs(x) / (x**2 + hw**2) ** 2
    s0 = 2 * HW**2 * (HW / np.sqrt(3)) / ((HW**2 / 3 + HW**2) ** 2)  # peak, beta=0
    return RPK * s / s0


# ---- calibration (done once, at beta = 0, like the real script) ----------
_xg = np.linspace(HW / np.sqrt(3), 6 * HW, 4000)          # outer flank
X0 = float(_xg[np.argmin(np.abs(lobe(_xg) - 0.45 * RPK))])  # setpoint: 45 % of peak
R0 = float(lobe(X0))
_d = 1e-5
D_CAL = float((lobe(X0 + _d) - lobe(X0 - _d)) / (2 * _d))   # V/MHz (<0)


def step(u, G, beta=0.0, noise=0.0):
    """One loop cycle: u is the detuning f - c."""
    R = lobe(u, beta) + noise
    return u - (G / D_CAL) * (R - R0)


def orbit(G, n=400, beta=0.0, sigma=0.0, u0=X0 + 0.05, rng=rng, drift=None):
    # note: u0 is seeded slightly OFF the fixed point, so an unstable lock
    # actually departs even in the noise-free (deterministic) runs
    """Iterate the map; returns the detuning trace. `drift` = per-step line-
    centre displacement array (enters as an equivalent detuning kick)."""
    u = np.empty(n)
    u[0] = u0
    for k in range(1, n):
        nz = sigma * rng.standard_normal() if sigma else 0.0
        u[k] = step(u[k - 1], G, beta, nz)
        if drift is not None:
            u[k] -= drift[k] - drift[k - 1]
        u[k] = np.clip(u[k], -CLIP, CLIP)
    return u


def orbit_amp(G, beta=0.0, sigma=0.0, n=600, keep=200, rng=rng):
    """Steady-state oscillation amplitude (std of the tail of the orbit)."""
    return float(np.std(orbit(G, n, beta, sigma, rng=rng)[-keep:]))


# ===========================================================================
# Fig 1: the system -- lobe + setpoint, and the map (cobweb) below/above onset
# ===========================================================================
def cobweb(ax, G, n=40, u0=None):
    xs = np.linspace(0.2, 3.2, 600)
    ax.plot(xs, [step(x, G) for x in xs], color="C0", lw=1.4,
            label=r"map $f_{k+1}(f_k)$")
    ax.plot(xs, xs, color="0.6", lw=1, ls="--", label="identity")
    u = u0 if u0 is not None else X0 + 0.55
    px, py = [u], [u]
    for _ in range(n):
        v = step(u, G)
        px += [u, v]
        py += [v, v]
        u = v
    ax.plot(px, py, color="C3", lw=0.8, alpha=0.85)
    ax.plot(X0, X0, "o", color="C2", ms=6)
    ax.set(xlabel=r"detuning $u_k$ [MHz]", ylabel=r"$u_{k+1}$ [MHz]",
           title=f"loop gain G = {G}")
    ax.grid(alpha=0.3)


fig, axes = plt.subplots(1, 3, figsize=(12, 3.6))
x = np.linspace(-4, 4, 1200)
axes[0].plot(x, 1e3 * lobe(x), color="C0", lw=1.4, label="unperturbed")
axes[0].plot(x, 1e3 * lobe(x, 0.3), color="C1", lw=1.2,
             label="slope-changing\nperturbation (+30 % width)")
axes[0].axhline(1e3 * R0, color="C2", ls=":", lw=1)
axes[0].plot(X0, 1e3 * R0, "o", color="C2", label=rf"setpoint $R_0$, $x_0$")
axes[0].set(xlabel="detuning from line centre [MHz]", ylabel="lock-in R [mV]",
            title="FM lobe = the nonlinearity of the loop")
axes[0].legend(fontsize=7)
axes[0].grid(alpha=0.3)
cobweb(axes[1], 1.0)
axes[1].set_title("G = 1.0: stable lock (tracker)")
cobweb(axes[2], 2.4)
axes[2].set_title("G = 2.4: autonomous limit cycle")
axes[1].legend(fontsize=7)
fig.tight_layout()
fig.savefig(os.path.join(HERE, "fig1_system_and_map.png"), dpi=150)
plt.close(fig)

# ===========================================================================
# Fig 2: bifurcation diagram (deterministic) -- the "device physics"
# ===========================================================================
Gs = np.linspace(0.4, 3.4, 800)
fig, ax = plt.subplots(figsize=(8, 4.2))
for G in Gs:
    tail = orbit(G, 500)[-60:]
    ax.plot([G] * len(tail), tail, ",", color="C0", alpha=0.5)
ax.axvline(2.0, color="C3", ls="--", lw=1)
ax.annotate("flip bifurcation\n$G_{eff}=2$: onset of\nself-oscillation",
            (2.02, 2.9), color="C3", fontsize=9)
ax.annotate("stable lock\n(ordinary magnetometer)", (0.7, 0.7), fontsize=9)
ax.annotate("period doubling\n-> chaos", (2.75, 4.4), fontsize=9)
ax.set(xlabel="loop gain G", ylabel="steady-state detuning $u_k$ [MHz]",
       title="The NV feedback loop as an autonomous nonlinear device")
ax.grid(alpha=0.3)
fig.tight_layout()
fig.savefig(os.path.join(HERE, "fig2_bifurcation.png"), dpi=150)
plt.close(fig)

# ===========================================================================
# Fig 3: the onset as a sensor of slope-type perturbations (e.g. gradients)
# ===========================================================================
betas = (0.0, 0.1, 0.2, 0.3)
Gs3 = np.linspace(1.5, 3.2, 120)
fig, (ax, ax2) = plt.subplots(1, 2, figsize=(10, 3.8))
for b, c in zip(betas, ("C0", "C2", "C1", "C3")):
    amp = [np.mean([orbit_amp(G, beta=b) for _ in range(1)]) for G in Gs3]
    ax.plot(Gs3, amp, color=c, lw=1.4, label=rf"$\beta$ = {b:.1f}")
ax.set(xlabel="loop gain G", ylabel="oscillation amplitude [MHz]",
       title="Perturbations move the onset of autonomy")
ax.legend(title="line broadening\n(gradient proxy)", fontsize=8)
ax.grid(alpha=0.3)

# threshold vs beta: smallest G with amplitude above a small cut
G_fine = np.linspace(1.6, 3.4, 400)
bet_fine = np.linspace(0, 0.35, 15)
thr = []
for b in bet_fine:
    a = np.array([orbit_amp(G, beta=b) for G in G_fine])
    idx = np.argmax(a > 0.05)
    thr.append(G_fine[idx] if a[idx] > 0.05 else np.nan)
ax2.plot(bet_fine, thr, "o-", color="C3")
ax2.set(xlabel=r"fractional line broadening $\beta$",
        ylabel="critical gain $G_c$",
        title=r"$G_c$ tracks the perturbation: threshold sensor")
ax2.grid(alpha=0.3)
fig.tight_layout()
fig.savefig(os.path.join(HERE, "fig3_onset_sensor.png"), dpi=150)
plt.close(fig)

# ===========================================================================
# Fig 4: with realistic noise -- P(oscillating) is a sharp discriminator
# ===========================================================================
G_OP = 2.35                      # operate slightly above the beta=0 threshold
def p_osc(beta, n_trials=60):
    amp0 = orbit_amp(1.0, sigma=SIG_R)          # noise-only reference
    hits = 0
    for _ in range(n_trials):
        if orbit_amp(G_OP, beta=beta, sigma=SIG_R) > 4 * amp0:
            hits += 1
    return hits / n_trials

bet4 = np.linspace(0, 0.30, 13)
p = [p_osc(b) for b in bet4]
fig, ax = plt.subplots(figsize=(6.4, 3.8))
ax.plot(bet4, p, "o-", color="C0")
ax.set(xlabel=r"line broadening $\beta$ (perturbation strength)",
       ylabel="P(self-oscillation) over repeated trials",
       title=f"Noisy threshold detection at fixed G = {G_OP}")
ax.grid(alpha=0.3)
fig.tight_layout()
fig.savefig(os.path.join(HERE, "fig4_threshold_detection.png"), dpi=150)
plt.close(fig)

# ===========================================================================
# Fig 5: time-periodic perturbation read out from the limit-cycle statistics
# ===========================================================================
G5, N5, F_SIG = 2.4, 6000, 7.0            # Hz signal, above loop bandwidth
t5 = np.arange(N5) * DT
def envelope(u, m=1):
    """Amplitude of the period-2 limit cycle: demodulate the alternating
    component s_k = (-1)^k (u_k - <u>) with a short moving average -- i.e. a
    lock-in ON the autonomous oscillation itself."""
    s = ((-1.0) ** np.arange(len(u))) * (u - np.mean(u))
    if m > 1:                       # keep m small: a boxcar of length m has
        s = np.convolve(s, np.ones(m) / m, mode="valid")   # nulls at fs/m !
    return s

for amp_sig, tag in ((0.0, "off"), (0.03, "on")):     # 30 kHz line dither @7 Hz
    drift = amp_sig * np.sin(2 * np.pi * F_SIG * t5)
    u = orbit(G5, N5, sigma=SIG_R, drift=drift)
    env = envelope(u)
    if tag == "off":
        env_off = env
    else:
        env_on = env

def asd(y, dt, n_seg=12):
    """Welch-averaged amplitude spectrum (smooth floor -> peaks stand out)."""
    y = np.asarray(y, float) - np.mean(y)
    seg = len(y) // n_seg
    w = np.hanning(seg)
    S = []
    for k in range(n_seg):
        x = y[k * seg:(k + 1) * seg]
        S.append((np.abs(np.fft.rfft((x - x.mean()) * w)) / np.sum(w) * 2) ** 2)
    return np.fft.rfftfreq(seg, dt), np.sqrt(np.mean(S, axis=0))

fig, (ax, ax2) = plt.subplots(1, 2, figsize=(10, 3.8))
u_show = orbit(G5, 80, sigma=SIG_R)
ax.plot(np.arange(80) * DT, u_show, "o-", ms=3, lw=0.7, color="C0")
ax.set(xlabel="time [s]", ylabel="detuning $u_k$ [MHz]",
       title=f"Autonomous limit cycle (G = {G5}): period-2 hopping")
ax.grid(alpha=0.3)
fr_off, S_off = asd(env_off, DT)
fr_on, S_on = asd(env_on, DT)
ax2.semilogy(fr_off[1:], S_off[1:], lw=1.1, color="0.55", label="perturbation off")
ax2.semilogy(fr_on[1:], S_on[1:], lw=1.1, color="C3", label="7 Hz field on")
f_mix = 1.0 / (2 * DT) - F_SIG          # period-2 cycle = internal LO at Nyquist
ax2.axvline(f_mix, color="C3", ls=":", lw=1)
ax2.annotate(f"mixing sideband\n{1/(2*DT):.0f} - {F_SIG:.0f} = {f_mix:.0f} Hz:\n"
             "the limit cycle acts as\nan internal local oscillator",
             (f_mix + 0.25, 0.06), color="C3", fontsize=8)
ax2.set(xlabel="frequency [Hz]", ylabel="demodulated cycle spectrum [MHz]",
        title="Signal read out from the oscillation STATISTICS")
ax2.legend(fontsize=8)
ax2.grid(alpha=0.3)
fig.tight_layout()
fig.savefig(os.path.join(HERE, "fig5_statistics_readout.png"), dpi=150)
plt.close(fig)

print(f"setpoint x0 = {X0:.3f} MHz, R0 = {1e3*R0:.2f} mV, "
      f"D_cal = {1e3*D_CAL:+.2f} mV/MHz")
print("figures written: fig1..fig5 in", HERE)
